### ISSUE TITLE
Practica 4 y 5

### ISSUE THREAD

**Issue by kirus21** [SistemasTecTlaxiaco/practica-4y5-team-pro-1#1]
[Practica 4 y 5.docx.pdf](https://github.com/SistemasTecTlaxiaco/practica-4y5-team-pro-1/files/8681283/Practica.4.y.5.docx.pdf)

**Comment by kirus21** [comment]
[Practica 4 y 5.docx.pdf](https://github.com/SistemasTecTlaxiaco/practica-4y5-team-pro-1/files/8681014/Practica.4.y.5.docx.pdf)

archivo modificado

**Comment by Abraham890** [comment]
Calificación: 20 puntos

**Comment by josealfredo79** [comment]
Bien hecho y revisado
